name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Static Files
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Step 2: Debug repository structure (Optional)
      - name: List repository files for debugging
        run: |
          echo "Repository files:"
          ls -R

      # Step 3: Build and Deploy to Azure Static Web App
      - name: Build and Deploy Static Front-End
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_WATER_0B1A3D20F }}
          action: "upload"
          app_location: "./static" # Path to the static folder containing your front-end files
          api_location: "" # No API is used for this deployment
          output_location: "." # No build output folder needed
