name: Build and Deploy to Azure Web App - lookapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 3: Run tests (optional)
      # Uncomment the following section if you have tests to run
      # - name: Run tests
      #   run: pytest

      # Step 4: Zip the application for deployment
      - name: Package application
        run: zip release.zip ./* -r -x "venv/*"

      # Step 5: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_264E190F46954F3FB12E12BE5D9F9B70 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B6A48E0380924A43A360AF80F427421A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_247B62E695784804A46D900278D9D0C8 }}
          auth-type: "SERVICE_PRINCIPAL"
          enable-AzPSSession: false
          environment: azurecloud
          audience: api://AzureADTokenExchange

      # Step 6: Deploy static files
      - name: Deploy static files
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lookapp'
          slot-name: 'Production'
          package: './static'

      # Step 7: Deploy backend code
      - name: Deploy backend code
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lookapp'
          slot-name: 'Production'
          package: './app'

      # Step 8: Final deploy artifact to Azure Web App
      - name: Deploy the app
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'lookapp'
          slot-name: 'Production'
          package: './release.zip'
